### PR TITLE
Update to 3.3.9 and enhancements

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR provides updates to the maven-formula which is bit out of date.  
Maven 3.3.9 is much more widely used than latest version (3.5).

Enhancements
----------------
- Maven 3.3.9
- full integration with linux alternatives
- add Desktop icon
- more pillar/grain lookups for settings.sls
- updated pillar.example

Tested Baseline
------------------
This snapshot was verified on Ubuntu 16 (earlier cut verified on Fedora 25)

Ubuntu 16.04 AMD Desktop release
+ xfce4 ssh software-properties-common lxde x2goserver x2goserver-xsession 
+ reboot host
+ add saltstack and execute formula

Fedora 25 AMD Desktop release
+ @Xfce @lxde-desktop x2goserver-xsession
+ reboot host
+ add saltstack and execute formula

Thanks,

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Comments on https://github.com/saltstack-formulas/sun-java-formula/pull/32 (contains similar patterns) need review/action before this PR is approved.

**Comment by noelmcloughlin** [comment]
Implemented the best practice comments from saltstack-formulas/sun-java-formula#32  review in this formula.  Tested on Ubuntu 16.04.

Please review and approve if happy.
 Thanks.

**Comment by noelmcloughlin** [comment]
@whiteinge Hi Seth, could you get someone to review.

**Comment by whiteinge** [comment]
@noelmcloughlin looks good, thanks!

**Comment by noelmcloughlin** [comment]
Thanks @whiteinge

**Pull request merged**
